dream:
  cache: com.dream.system.cache.MemoryCache
  listeners:
    - com.dream.drive.listener.DebugListener
  mapperPackages:
    - com.dream.helloworld
  tablePackages:
    - com.dream.helloworld

  datasource:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.0.242/d-open-sun
      username: root
      password: BMW#Halu@1234%
    slave:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.0.242/d-open-wqt
      username: root
      password: BMW#Halu@1234%
