solon.app:
  name: demoapp
  group: demo

solon.output.meta: 1

test.db1:
  schema: solon
  jdbcUrl: jdbc:mysql://192.168.0.3:3306/solon?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: BMW#Halu@1234%
  url: ${test.db1.jdbcUrl}

# 这是dream自定义动态数据源，在启动类加上@EnableShare才能开启
dream:
  datasource:
    master:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.0.3/d-open
      username: root
      password: BMW#Halu@1234%
      keepaliveTime: 1000
      isReadOnly: false
    slave:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.0.3/d-open-6c
      username: root
      password: BMW#Halu@1234%
