dream:
  cache: com.dream.system.cache.MemoryCache
  listeners:
    - com.dream.drive.listener.DebugListener
    - com.dream.helloworld.h2.DataAuditListener
  mapperPackages:
    - com.dream.helloworld
  tablePackages:
    - com.dream.helloworld
