spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost/sooth
      username: root
      password: 123456

  dream:
    toSQL: com.dream.antlr.sql.ToMySQL
    listeners:
      - com.dream.drive.listener.DebugListener
